### ISSUE TITLE
Transaction gas fees / uniswap

### ISSUE THREAD

**Issue by gwendall** [jklepatch/eattheblocks#45]
First, thanks for the great content !

Quick question: is there a way to set the gas fees we would like to pay for a transaction calling the `swapExactTokensForTokens` method ? 

Here is what I have for now:

```
const tx = await router.swapExactTokensForTokens(
  amountIn,
  amountOutMin,
  [tokenIn, tokenOut],
  recipientAddress,
  expiryDate,
);
const receipt = await tx.wait();
```

**Comment by djammy33** [comment]
thak you gwendall!!👍👌

**Comment by ivekivek** [comment]
It should work if you add limit and price manual like this. It works on Uniswap

`const tx = await router.swapExactTokensForTokens(
    amountIn,
    amountOutMin,
    [tokenIn, tokenOut],
    addresses.recipient,
    //{ gasPrice: 100000000 },
    //ethers.utils.parseTransaction({ gasPrice: 10000 })
    {
      value: '0',
      gasPrice: ethers.BigNumber.from(1000000).toHexString(),
      gasLimit: ethers.BigNumber.from(1000000).toHexString() 
    },
    Date.now() + 1000 * 60 * 10, // 10 minutes
  );`

**Comment by tuxforensics** [comment]
Was this resolved?  How do you set gas and gas limit..
